#!/bin/bash
cd $HOME/Pictures/Wallpapers/
file=$(yad --width 1200 --height 800 --file --add-preview --large-preview --title='Choose wallpaper')
if [[ $file == *.gif ]]; then
  if [[ ! -f ${file//.gif/.png} ]]; then
    magick $file[0] ${file//.gif/.png}
  fi
  setsid $HOME/.config/ags/scripts/color_generation/switchwall.sh $file &
elif [[ $file == *.webp ]]; then
  if [[ ! -f ${file//.webp/.png} ]]; then
    magick $file ${file//.webp/.png}
  fi
  setsid $HOME/.config/ags/scripts/color_generation/switchwall.sh $file &
else
  exit 1
fi

cp ${file%.*}.png $HOME/Pictures/Wallpapers/background.png
sudo cp ${file%.*}.png /usr/share/sddm/themes/sddm-astronaut-theme/Backgrounds/background.png
