keymap:
  - name: Right Alt + HJKL to Arrow Keys
    remap:
      Ctrl_R: Reserved
      Ctrl_R-h: Left
      Ctrl_R-j: Down
      Ctrl_R-K: Up
      Ctrl_R-l: Right

modmap:
  - name: CapsLock to RightCtrl/Esc
    remap:
      CapsLock:
        held: Ctrl_R
        alone: Esc
        alone_timeout: 500
