modmap:
  - name: CapsLock to RightCtrl/Esc
    remap:
      CapsLock: Ctrl_R

keymap:
  - name: Right Alt + HJKL to Arrow Keys
    remap:
      Ctrl_R: Reserved
      Ctrl_R-h: Left
      Ctrl_R-j: Down
      Ctrl_R-k: Up
      Ctrl_R-l: Right
  - name: Fn Keys
    remap:
      F6: Mute
      F7: VolumeDown
      F8: VolumeUp
      Mute: F6
      VolumeDown: F7
      VolumeUp: F8
  - name: CapsLock + HJKL → Arrow Keys
    remap:
      CapsLock-h: Left
      CapsLock-j: Down
      CapsLock-k: Up
      CapsLock-l: Right

  - name: CapsLock + Left/Right → Home/End
    remap:
      CapsLock-Left: Home
      CapsLock-Right: End
