#!/usr/bin/env sh

UPDATES=$(checkupdates & yay -Qua)
echo "{\"text\": \"$(echo -n "$UPDATES" | wc -l)\", \"tooltip\": \"$(echo -n "$UPDATES" | cut -f1 -d" " | sed -E ':a;N;$!ba;s/\r{0,1}\n/\r/g')\"}"
