#!/usr/bin/env sh

# UPDATES=$(checkupdates & yay -Qua)
echo "{\"text\": \"$((checkupdates & yay -Qua) | wc -l)\", \"tooltip\": \"$((checkupdates & echo '---------------' & yay -Qua) | cut -f1 -d" " | sed -E ':a;N;$!ba;s/\r{0,1}\n/\r/g')\"}"
# echo "{\"text\": \"$(echo -n "$UPDATES" | wc -l)\", \"tooltip\": \"$(echo -n "$UPDATES" | cut -f1 -d" " | sed -E ':a;N;$!ba;s/\r{0,1}\n/\r/g')\"}"
# echo "{\"text\": \"0\", \"tootip\": \"\"}"

