#!/usr/bin/env bash

SPECIAL_WINDOW_DOWN='music'
SPECIAL_WINDOW_UP='discord'

FOCUSED_MONITOR=`hyprctl -j monitors | jq -r '.[] | select(.focused == true) | .id'`


ACTIVE_WORKSPACE=`hyprctl -j activewindow | jq -r .workspace.name`
if [[ $1 == "up" ]]; then
    if [[ $ACTIVE_WORKSPACE == "special:$SPECIAL_WINDOW_DOWN" ]]; then
        hyprctl dispatch togglespecialworkspace $SPECIAL_WINDOW_DOWN
    else
        if [[ -z $(hyprctl -j monitors | jq -r ".[] | select(.id == $FOCUSED_MONITOR) | .specialWorkspace.name") ]]; then
            hyprctl dispatch togglespecialworkspace $SPECIAL_WINDOW_UP
        fi
    fi
elif [[ $1 == "down" ]]; then
    if [[ $ACTIVE_WORKSPACE == "special:$SPECIAL_WINDOW_UP" ]]; then
        hyprctl dispatch togglespecialworkspace $SPECIAL_WINDOW_UP
    else
        if [[ -z $(hyprctl -j monitors | jq -r ".[] | select(.id == $FOCUSED_MONITOR) | .specialWorkspace.name") ]]; then
            hyprctl dispatch togglespecialworkspace $SPECIAL_WINDOW_DOWN
        fi
    fi
fi
